### ISSUE TITLE
Set up CI pipeline and version release system in syft-proto with Github actions

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/syft-proto#36]
In theory, the syft-proto project will drive a lot of class creation in PySyft when those classes will inevitably be used by a worker library (syft.js, KotlinSyft, or SwiftSyft). In order to avoid issues of subtleties existing between various versions of OpenMined projects, it may be best to centralize all continuous integration, end-to-end testing, and version release management into one place. This isn't an issue that necessitates a code change (but if it does, it should be fairly minimal), but more a designation that we will need to hook up all the projects together into a CI pipeline that is run on an interval and runs our end-to-end tests (https://github.com/OpenMined/syft-proto/issues/37). This ensures that all versions of the workers are compatible with PySyft and PyGrid. This will allows to almost catch issues before our users do.

**Comment by karlhigley** [comment]
What's left to do to in order to close this issue? I think we've got Python, Java, and Swift packages being built from the automated Actions, yeah?

**Comment by cereallarceny** [comment]
I was thinking we would have the ability to test each library that claims syft-proto as a dependency with the latest version of the library every time it’s updated.  Basically ensuring that each of our projects continues to work as expected when a new syft-proto version is released.

**Comment by karlhigley** [comment]
Ah, okay. What we have at the moment is breaking change detection on the schemas, which will tell us when Protobuf changes will definitely break the downstream projects, but doesn't tell us that the downstream projects still work as expected for (assumed) non-breaking changes.

**Comment by cereallarceny** [comment]
Ahh that’s good enough for me then.  If you think we’re good here, feel free to close.  It seems like the scope of this issue has changed.

**Comment by cereallarceny** [comment]
I don't believe this issue is currently relevant and will be handled by the new release management team.
