### ISSUE TITLE
Tags are missing for versions of syft-proto that were pushed to pypi

### ISSUE THREAD

**Issue by GregoryLand** [OpenMined/syft-proto#56]
Several versions of 0.1.1a1 that are in pypi are missing.  The versions in question have a .post## naming convention.  The 0.1.1a1.post20 and 0.1.1a1 versions have significant differences between them.  Could tags be added for these missing releases?

**Comment by karlhigley** [comment]
@GregoryLand There aren’t tags because those were development versions. The `postXXX` part counts how commits since the last tagged versions. What would tags help you do?

**Comment by GregoryLand** [comment]
I have a package of syft for Arch Linux that seems to target a version of syft-proto in between version 0.1.1a1 and 0.1.1a1.post20.  Most likely post15.  This could be a result of a mistake made during the build process on our end.  If we retarget syft to 0.1.1.a1.post15 of syft-proto then the version of pyGrid we are using stops crashing on init of the worker docker containers.  I realize this particular usecase is probably outside of the green path.

**Comment by karlhigley** [comment]
Ah, makes sense. We had some difficulties with versioning and dependencies in PySyft. I'll tag the last few dev versions.

**Comment by GregoryLand** [comment]
Thank you!

**Comment by karlhigley** [comment]
These are the last few versions before v0.2.1.a1:
* https://github.com/OpenMined/syft-proto/releases/tag/v0.1.1.a1.post15
* https://github.com/OpenMined/syft-proto/releases/tag/v0.1.1.a1.post17
